### ISSUE TITLE
checklist do report

### ISSUE THREAD

**Issue by philsf** [philsf-biostat/SAR-2021-008-JB#6]
- [ ] Title
- [ ] Objective
- [ ] Context (from SAP)
- [ ] Data & Methods (from SAP)
- [ ] Conclusions match the results
- [ ] Observations
- [ ] remove watermark
- [ ] update TOC
- [ ] render private + public version
